# Start with the base image
FROM shufangwu/ppr-meta:1.0

# Set the default working directory to /home/PPR-Meta
WORKDIR /home/PPR-Meta

# (Optional) Define the default command to run
CMD ["./PPR_Meta"]
