read1:
  class: File
  path: /media/franky/Seagate_Basic/Università/virfinder/input/HV04_R1.fq.gz
read2:
  class: File 
  path: /media/franky/Seagate_Basic/Università/virfinder/input/HV04_R2.fq.gz
fasta_file:
  class: File
  path: /home/franky/Downloads/HV04_short.fasta
threads: 12
database:
  class: Directory
  path: /home/franky/Downloads/genomad_db